/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerCreateConsentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerCreateConsentRequest{}

// CustomerCreateConsentRequest struct for CustomerCreateConsentRequest
type CustomerCreateConsentRequest struct {
	Preferences *map[string]bool `json:"preferences,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerCreateConsentRequest CustomerCreateConsentRequest

// NewCustomerCreateConsentRequest instantiates a new CustomerCreateConsentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerCreateConsentRequest() *CustomerCreateConsentRequest {
	this := CustomerCreateConsentRequest{}
	return &this
}

// NewCustomerCreateConsentRequestWithDefaults instantiates a new CustomerCreateConsentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerCreateConsentRequestWithDefaults() *CustomerCreateConsentRequest {
	this := CustomerCreateConsentRequest{}
	return &this
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *CustomerCreateConsentRequest) GetPreferences() map[string]bool {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]bool
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateConsentRequest) GetPreferencesOk() (*map[string]bool, bool) {
	if o == nil || IsNil(o.Preferences) {
		return nil, false
	}
	return o.Preferences, true
}

// &#39;Has&#39;Preferences returns a boolean if a field has been set.
func (o *CustomerCreateConsentRequest) &#39;Has&#39;Preferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]bool and assigns it to the Preferences field.
func (o *CustomerCreateConsentRequest) SetPreferences(v map[string]bool) {
	o.Preferences = &v
}

func (o CustomerCreateConsentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerCreateConsentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerCreateConsentRequest) UnmarshalJSON(data []byte) (err error) {
	varCustomerCreateConsentRequest := _CustomerCreateConsentRequest{}

	err = json.Unmarshal(data, &varCustomerCreateConsentRequest)

	if err != nil {
		return err
	}

	*o = CustomerCreateConsentRequest(varCustomerCreateConsentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "preferences")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerCreateConsentRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *CustomerCreateConsentRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableCustomerCreateConsentRequest struct {
	value *CustomerCreateConsentRequest
	isSet bool
}

func (v NullableCustomerCreateConsentRequest) Get() *CustomerCreateConsentRequest {
	return v.value
}

func (v *NullableCustomerCreateConsentRequest) Set(val *CustomerCreateConsentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerCreateConsentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerCreateConsentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerCreateConsentRequest(val *CustomerCreateConsentRequest) *NullableCustomerCreateConsentRequest {
	return &NullableCustomerCreateConsentRequest{value: val, isSet: true}
}

func (v NullableCustomerCreateConsentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerCreateConsentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


