/*
customer/customer.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomerCreateGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerCreateGroupRequest{}

// CustomerCreateGroupRequest struct for CustomerCreateGroupRequest
type CustomerCreateGroupRequest struct {
	Name *string `json:"name,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewCustomerCreateGroupRequest instantiates a new CustomerCreateGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerCreateGroupRequest() *CustomerCreateGroupRequest {
	this := CustomerCreateGroupRequest{}
	return &this
}

// NewCustomerCreateGroupRequestWithDefaults instantiates a new CustomerCreateGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerCreateGroupRequestWithDefaults() *CustomerCreateGroupRequest {
	this := CustomerCreateGroupRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CustomerCreateGroupRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateGroupRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CustomerCreateGroupRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CustomerCreateGroupRequest) SetName(v string) {
	o.Name = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerCreateGroupRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateGroupRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerCreateGroupRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerCreateGroupRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CustomerCreateGroupRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerCreateGroupRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CustomerCreateGroupRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CustomerCreateGroupRequest) SetCode(v string) {
	o.Code = &v
}

func (o CustomerCreateGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerCreateGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableCustomerCreateGroupRequest struct {
	value *CustomerCreateGroupRequest
	isSet bool
}

func (v NullableCustomerCreateGroupRequest) Get() *CustomerCreateGroupRequest {
	return v.value
}

func (v *NullableCustomerCreateGroupRequest) Set(val *CustomerCreateGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerCreateGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerCreateGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerCreateGroupRequest(val *CustomerCreateGroupRequest) *NullableCustomerCreateGroupRequest {
	return &NullableCustomerCreateGroupRequest{value: val, isSet: true}
}

func (v NullableCustomerCreateGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerCreateGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


