/*
customer/customer.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomerAddressDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerAddressDeleteRequest{}

// CustomerAddressDeleteRequest struct for CustomerAddressDeleteRequest
type CustomerAddressDeleteRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CustomerId *string `json:"customerId,omitempty"`
	AddressId *string `json:"addressId,omitempty"`
}

// NewCustomerAddressDeleteRequest instantiates a new CustomerAddressDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerAddressDeleteRequest() *CustomerAddressDeleteRequest {
	this := CustomerAddressDeleteRequest{}
	return &this
}

// NewCustomerAddressDeleteRequestWithDefaults instantiates a new CustomerAddressDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerAddressDeleteRequestWithDefaults() *CustomerAddressDeleteRequest {
	this := CustomerAddressDeleteRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerAddressDeleteRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAddressDeleteRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerAddressDeleteRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerAddressDeleteRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerAddressDeleteRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAddressDeleteRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerAddressDeleteRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerAddressDeleteRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *CustomerAddressDeleteRequest) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAddressDeleteRequest) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *CustomerAddressDeleteRequest) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *CustomerAddressDeleteRequest) SetAddressId(v string) {
	o.AddressId = &v
}

func (o CustomerAddressDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerAddressDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}
	return toSerialize, nil
}

type NullableCustomerAddressDeleteRequest struct {
	value *CustomerAddressDeleteRequest
	isSet bool
}

func (v NullableCustomerAddressDeleteRequest) Get() *CustomerAddressDeleteRequest {
	return v.value
}

func (v *NullableCustomerAddressDeleteRequest) Set(val *CustomerAddressDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAddressDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAddressDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerAddressDeleteRequest(val *CustomerAddressDeleteRequest) *NullableCustomerAddressDeleteRequest {
	return &NullableCustomerAddressDeleteRequest{value: val, isSet: true}
}

func (v NullableCustomerAddressDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAddressDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


