/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerRemoveCustomerFromGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerRemoveCustomerFromGroupRequest{}

// CustomerRemoveCustomerFromGroupRequest struct for CustomerRemoveCustomerFromGroupRequest
type CustomerRemoveCustomerFromGroupRequest struct {
	TenantId             *string `json:"tenantId,omitempty"`
	GroupId              *string `json:"groupId,omitempty"`
	CustomerId           *string `json:"customerId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerRemoveCustomerFromGroupRequest CustomerRemoveCustomerFromGroupRequest

// NewCustomerRemoveCustomerFromGroupRequest instantiates a new CustomerRemoveCustomerFromGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerRemoveCustomerFromGroupRequest() *CustomerRemoveCustomerFromGroupRequest {
	this := CustomerRemoveCustomerFromGroupRequest{}
	return &this
}

// NewCustomerRemoveCustomerFromGroupRequestWithDefaults instantiates a new CustomerRemoveCustomerFromGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerRemoveCustomerFromGroupRequestWithDefaults() *CustomerRemoveCustomerFromGroupRequest {
	this := CustomerRemoveCustomerFromGroupRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerRemoveCustomerFromGroupRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerRemoveCustomerFromGroupRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *CustomerRemoveCustomerFromGroupRequest) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *CustomerRemoveCustomerFromGroupRequest) SetGroupId(v string) {
	o.GroupId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerRemoveCustomerFromGroupRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerRemoveCustomerFromGroupRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerRemoveCustomerFromGroupRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

func (o CustomerRemoveCustomerFromGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerRemoveCustomerFromGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerRemoveCustomerFromGroupRequest) UnmarshalJSON(data []byte) (err error) {
	varCustomerRemoveCustomerFromGroupRequest := _CustomerRemoveCustomerFromGroupRequest{}

	err = json.Unmarshal(data, &varCustomerRemoveCustomerFromGroupRequest)

	if err != nil {
		return err
	}

	*o = CustomerRemoveCustomerFromGroupRequest(varCustomerRemoveCustomerFromGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "groupId")
		delete(additionalProperties, "customerId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerRemoveCustomerFromGroupRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *CustomerRemoveCustomerFromGroupRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableCustomerRemoveCustomerFromGroupRequest struct {
	value *CustomerRemoveCustomerFromGroupRequest
	isSet bool
}

func (v NullableCustomerRemoveCustomerFromGroupRequest) Get() *CustomerRemoveCustomerFromGroupRequest {
	return v.value
}

func (v *NullableCustomerRemoveCustomerFromGroupRequest) Set(val *CustomerRemoveCustomerFromGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerRemoveCustomerFromGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerRemoveCustomerFromGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerRemoveCustomerFromGroupRequest(val *CustomerRemoveCustomerFromGroupRequest) *NullableCustomerRemoveCustomerFromGroupRequest {
	return &NullableCustomerRemoveCustomerFromGroupRequest{value: val, isSet: true}
}

func (v NullableCustomerRemoveCustomerFromGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerRemoveCustomerFromGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
