/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerSearchResponse{}

// CustomerSearchResponse struct for CustomerSearchResponse
type CustomerSearchResponse struct {
	Customers            []CustomerCustomerResponse `json:"customers,omitempty"`
	NextPageToken        *string                    `json:"nextPageToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerSearchResponse CustomerSearchResponse

// NewCustomerSearchResponse instantiates a new CustomerSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerSearchResponse() *CustomerSearchResponse {
	this := CustomerSearchResponse{}
	return &this
}

// NewCustomerSearchResponseWithDefaults instantiates a new CustomerSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerSearchResponseWithDefaults() *CustomerSearchResponse {
	this := CustomerSearchResponse{}
	return &this
}

// GetCustomers returns the Customers field value if set, zero value otherwise.
func (o *CustomerSearchResponse) GetCustomers() []CustomerCustomerResponse {
	if o == nil || IsNil(o.Customers) {
		var ret []CustomerCustomerResponse
		return ret
	}
	return o.Customers
}

// GetCustomersOk returns a tuple with the Customers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSearchResponse) GetCustomersOk() ([]CustomerCustomerResponse, bool) {
	if o == nil || IsNil(o.Customers) {
		return nil, false
	}
	return o.Customers, true
}

// HasCustomers returns a boolean if a field has been set.
func (o *CustomerSearchResponse) HasCustomers() bool {
	if o != nil && !IsNil(o.Customers) {
		return true
	}

	return false
}

// SetCustomers gets a reference to the given []CustomerCustomerResponse and assigns it to the Customers field.
func (o *CustomerSearchResponse) SetCustomers(v []CustomerCustomerResponse) {
	o.Customers = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *CustomerSearchResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerSearchResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *CustomerSearchResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *CustomerSearchResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o CustomerSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Customers) {
		toSerialize["customers"] = o.Customers
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerSearchResponse) UnmarshalJSON(data []byte) (err error) {
	varCustomerSearchResponse := _CustomerSearchResponse{}

	err = json.Unmarshal(data, &varCustomerSearchResponse)

	if err != nil {
		return err
	}

	*o = CustomerSearchResponse(varCustomerSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customers")
		delete(additionalProperties, "nextPageToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerSearchResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *CustomerSearchResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableCustomerSearchResponse struct {
	value *CustomerSearchResponse
	isSet bool
}

func (v NullableCustomerSearchResponse) Get() *CustomerSearchResponse {
	return v.value
}

func (v *NullableCustomerSearchResponse) Set(val *CustomerSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerSearchResponse(val *CustomerSearchResponse) *NullableCustomerSearchResponse {
	return &NullableCustomerSearchResponse{value: val, isSet: true}
}

func (v NullableCustomerSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
