/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerFindManyRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerFindManyRequestFilter{}

// CustomerFindManyRequestFilter struct for CustomerFindManyRequestFilter
type CustomerFindManyRequestFilter struct {
	Newsletter *bool `json:"newsletter,omitempty"`
	AgentGrn *string `json:"agentGrn,omitempty"`
}

// NewCustomerFindManyRequestFilter instantiates a new CustomerFindManyRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFindManyRequestFilter() *CustomerFindManyRequestFilter {
	this := CustomerFindManyRequestFilter{}
	return &this
}

// NewCustomerFindManyRequestFilterWithDefaults instantiates a new CustomerFindManyRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFindManyRequestFilterWithDefaults() *CustomerFindManyRequestFilter {
	this := CustomerFindManyRequestFilter{}
	return &this
}

// GetNewsletter returns the Newsletter field value if set, zero value otherwise.
func (o *CustomerFindManyRequestFilter) GetNewsletter() bool {
	if o == nil || IsNil(o.Newsletter) {
		var ret bool
		return ret
	}
	return *o.Newsletter
}

// GetNewsletterOk returns a tuple with the Newsletter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindManyRequestFilter) GetNewsletterOk() (*bool, bool) {
	if o == nil || IsNil(o.Newsletter) {
		return nil, false
	}
	return o.Newsletter, true
}

// HasNewsletter returns a boolean if a field has been set.
func (o *CustomerFindManyRequestFilter) HasNewsletter() bool {
	if o != nil && !IsNil(o.Newsletter) {
		return true
	}

	return false
}

// SetNewsletter gets a reference to the given bool and assigns it to the Newsletter field.
func (o *CustomerFindManyRequestFilter) SetNewsletter(v bool) {
	o.Newsletter = &v
}

// GetAgentGrn returns the AgentGrn field value if set, zero value otherwise.
func (o *CustomerFindManyRequestFilter) GetAgentGrn() string {
	if o == nil || IsNil(o.AgentGrn) {
		var ret string
		return ret
	}
	return *o.AgentGrn
}

// GetAgentGrnOk returns a tuple with the AgentGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindManyRequestFilter) GetAgentGrnOk() (*string, bool) {
	if o == nil || IsNil(o.AgentGrn) {
		return nil, false
	}
	return o.AgentGrn, true
}

// HasAgentGrn returns a boolean if a field has been set.
func (o *CustomerFindManyRequestFilter) HasAgentGrn() bool {
	if o != nil && !IsNil(o.AgentGrn) {
		return true
	}

	return false
}

// SetAgentGrn gets a reference to the given string and assigns it to the AgentGrn field.
func (o *CustomerFindManyRequestFilter) SetAgentGrn(v string) {
	o.AgentGrn = &v
}

func (o CustomerFindManyRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerFindManyRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Newsletter) {
		toSerialize["newsletter"] = o.Newsletter
	}
	if !IsNil(o.AgentGrn) {
		toSerialize["agentGrn"] = o.AgentGrn
	}
	return toSerialize, nil
}

type NullableCustomerFindManyRequestFilter struct {
	value *CustomerFindManyRequestFilter
	isSet bool
}

func (v NullableCustomerFindManyRequestFilter) Get() *CustomerFindManyRequestFilter {
	return v.value
}

func (v *NullableCustomerFindManyRequestFilter) Set(val *CustomerFindManyRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFindManyRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFindManyRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFindManyRequestFilter(val *CustomerFindManyRequestFilter) *NullableCustomerFindManyRequestFilter {
	return &NullableCustomerFindManyRequestFilter{value: val, isSet: true}
}

func (v NullableCustomerFindManyRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFindManyRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


