/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerRemoveDefaultAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerRemoveDefaultAddressRequest{}

// CustomerRemoveDefaultAddressRequest struct for CustomerRemoveDefaultAddressRequest
type CustomerRemoveDefaultAddressRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CustomerId *string `json:"customerId,omitempty"`
	AddressId *string `json:"addressId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerRemoveDefaultAddressRequest CustomerRemoveDefaultAddressRequest

// NewCustomerRemoveDefaultAddressRequest instantiates a new CustomerRemoveDefaultAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerRemoveDefaultAddressRequest() *CustomerRemoveDefaultAddressRequest {
	this := CustomerRemoveDefaultAddressRequest{}
	return &this
}

// NewCustomerRemoveDefaultAddressRequestWithDefaults instantiates a new CustomerRemoveDefaultAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerRemoveDefaultAddressRequestWithDefaults() *CustomerRemoveDefaultAddressRequest {
	this := CustomerRemoveDefaultAddressRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerRemoveDefaultAddressRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveDefaultAddressRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerRemoveDefaultAddressRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerRemoveDefaultAddressRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerRemoveDefaultAddressRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveDefaultAddressRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerRemoveDefaultAddressRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerRemoveDefaultAddressRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *CustomerRemoveDefaultAddressRequest) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerRemoveDefaultAddressRequest) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *CustomerRemoveDefaultAddressRequest) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *CustomerRemoveDefaultAddressRequest) SetAddressId(v string) {
	o.AddressId = &v
}

func (o CustomerRemoveDefaultAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerRemoveDefaultAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerRemoveDefaultAddressRequest) UnmarshalJSON(data []byte) (err error) {
	varCustomerRemoveDefaultAddressRequest := _CustomerRemoveDefaultAddressRequest{}

	err = json.Unmarshal(data, &varCustomerRemoveDefaultAddressRequest)

	if err != nil {
		return err
	}

	*o = CustomerRemoveDefaultAddressRequest(varCustomerRemoveDefaultAddressRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "customerId")
		delete(additionalProperties, "addressId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerRemoveDefaultAddressRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *CustomerRemoveDefaultAddressRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableCustomerRemoveDefaultAddressRequest struct {
	value *CustomerRemoveDefaultAddressRequest
	isSet bool
}

func (v NullableCustomerRemoveDefaultAddressRequest) Get() *CustomerRemoveDefaultAddressRequest {
	return v.value
}

func (v *NullableCustomerRemoveDefaultAddressRequest) Set(val *CustomerRemoveDefaultAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerRemoveDefaultAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerRemoveDefaultAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerRemoveDefaultAddressRequest(val *CustomerRemoveDefaultAddressRequest) *NullableCustomerRemoveDefaultAddressRequest {
	return &NullableCustomerRemoveDefaultAddressRequest{value: val, isSet: true}
}

func (v NullableCustomerRemoveDefaultAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerRemoveDefaultAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


