/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerListGroupsRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerListGroupsRequestFilter{}

// CustomerListGroupsRequestFilter struct for CustomerListGroupsRequestFilter
type CustomerListGroupsRequestFilter struct {
	SearchTerm *string `json:"searchTerm,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerListGroupsRequestFilter CustomerListGroupsRequestFilter

// NewCustomerListGroupsRequestFilter instantiates a new CustomerListGroupsRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerListGroupsRequestFilter() *CustomerListGroupsRequestFilter {
	this := CustomerListGroupsRequestFilter{}
	return &this
}

// NewCustomerListGroupsRequestFilterWithDefaults instantiates a new CustomerListGroupsRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerListGroupsRequestFilterWithDefaults() *CustomerListGroupsRequestFilter {
	this := CustomerListGroupsRequestFilter{}
	return &this
}

// GetSearchTerm returns the SearchTerm field value if set, zero value otherwise.
func (o *CustomerListGroupsRequestFilter) GetSearchTerm() string {
	if o == nil || IsNil(o.SearchTerm) {
		var ret string
		return ret
	}
	return *o.SearchTerm
}

// GetSearchTermOk returns a tuple with the SearchTerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerListGroupsRequestFilter) GetSearchTermOk() (*string, bool) {
	if o == nil || IsNil(o.SearchTerm) {
		return nil, false
	}
	return o.SearchTerm, true
}

// HasSearchTerm returns a boolean if a field has been set.
func (o *CustomerListGroupsRequestFilter) HasSearchTerm() bool {
	if o != nil && !IsNil(o.SearchTerm) {
		return true
	}

	return false
}

// SetSearchTerm gets a reference to the given string and assigns it to the SearchTerm field.
func (o *CustomerListGroupsRequestFilter) SetSearchTerm(v string) {
	o.SearchTerm = &v
}

func (o CustomerListGroupsRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerListGroupsRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SearchTerm) {
		toSerialize["searchTerm"] = o.SearchTerm
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerListGroupsRequestFilter) UnmarshalJSON(data []byte) (err error) {
	varCustomerListGroupsRequestFilter := _CustomerListGroupsRequestFilter{}

	err = json.Unmarshal(data, &varCustomerListGroupsRequestFilter)

	if err != nil {
		return err
	}

	*o = CustomerListGroupsRequestFilter(varCustomerListGroupsRequestFilter)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "searchTerm")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerListGroupsRequestFilter) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *CustomerListGroupsRequestFilter) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableCustomerListGroupsRequestFilter struct {
	value *CustomerListGroupsRequestFilter
	isSet bool
}

func (v NullableCustomerListGroupsRequestFilter) Get() *CustomerListGroupsRequestFilter {
	return v.value
}

func (v *NullableCustomerListGroupsRequestFilter) Set(val *CustomerListGroupsRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerListGroupsRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerListGroupsRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerListGroupsRequestFilter(val *CustomerListGroupsRequestFilter) *NullableCustomerListGroupsRequestFilter {
	return &NullableCustomerListGroupsRequestFilter{value: val, isSet: true}
}

func (v NullableCustomerListGroupsRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerListGroupsRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


