/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the ListConsentsRequestFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListConsentsRequestFilters{}

// ListConsentsRequestFilters struct for ListConsentsRequestFilters
type ListConsentsRequestFilters struct {
	SubjectIds []string `json:"subjectIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListConsentsRequestFilters ListConsentsRequestFilters

// NewListConsentsRequestFilters instantiates a new ListConsentsRequestFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConsentsRequestFilters() *ListConsentsRequestFilters {
	this := ListConsentsRequestFilters{}
	return &this
}

// NewListConsentsRequestFiltersWithDefaults instantiates a new ListConsentsRequestFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConsentsRequestFiltersWithDefaults() *ListConsentsRequestFilters {
	this := ListConsentsRequestFilters{}
	return &this
}

// GetSubjectIds returns the SubjectIds field value if set, zero value otherwise.
func (o *ListConsentsRequestFilters) GetSubjectIds() []string {
	if o == nil || IsNil(o.SubjectIds) {
		var ret []string
		return ret
	}
	return o.SubjectIds
}

// GetSubjectIdsOk returns a tuple with the SubjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConsentsRequestFilters) GetSubjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubjectIds) {
		return nil, false
	}
	return o.SubjectIds, true
}

// &#39;Has&#39;SubjectIds returns a boolean if a field has been set.
func (o *ListConsentsRequestFilters) &#39;Has&#39;SubjectIds() bool {
	if o != nil && !IsNil(o.SubjectIds) {
		return true
	}

	return false
}

// SetSubjectIds gets a reference to the given []string and assigns it to the SubjectIds field.
func (o *ListConsentsRequestFilters) SetSubjectIds(v []string) {
	o.SubjectIds = v
}

func (o ListConsentsRequestFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListConsentsRequestFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubjectIds) {
		toSerialize["subjectIds"] = o.SubjectIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListConsentsRequestFilters) UnmarshalJSON(data []byte) (err error) {
	varListConsentsRequestFilters := _ListConsentsRequestFilters{}

	err = json.Unmarshal(data, &varListConsentsRequestFilters)

	if err != nil {
		return err
	}

	*o = ListConsentsRequestFilters(varListConsentsRequestFilters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subjectIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ListConsentsRequestFilters) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *ListConsentsRequestFilters) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableListConsentsRequestFilters struct {
	value *ListConsentsRequestFilters
	isSet bool
}

func (v NullableListConsentsRequestFilters) Get() *ListConsentsRequestFilters {
	return v.value
}

func (v *NullableListConsentsRequestFilters) Set(val *ListConsentsRequestFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableListConsentsRequestFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableListConsentsRequestFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConsentsRequestFilters(val *ListConsentsRequestFilters) *NullableListConsentsRequestFilters {
	return &NullableListConsentsRequestFilters{value: val, isSet: true}
}

func (v NullableListConsentsRequestFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConsentsRequestFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


