/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerUnassignAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerUnassignAgentRequest{}

// CustomerUnassignAgentRequest struct for CustomerUnassignAgentRequest
type CustomerUnassignAgentRequest struct {
	TenantId             *string  `json:"tenantId,omitempty"`
	AgentGrn             *string  `json:"agentGrn,omitempty"`
	CustomerIds          []string `json:"customerIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerUnassignAgentRequest CustomerUnassignAgentRequest

// NewCustomerUnassignAgentRequest instantiates a new CustomerUnassignAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerUnassignAgentRequest() *CustomerUnassignAgentRequest {
	this := CustomerUnassignAgentRequest{}
	return &this
}

// NewCustomerUnassignAgentRequestWithDefaults instantiates a new CustomerUnassignAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerUnassignAgentRequestWithDefaults() *CustomerUnassignAgentRequest {
	this := CustomerUnassignAgentRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerUnassignAgentRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUnassignAgentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerUnassignAgentRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerUnassignAgentRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetAgentGrn returns the AgentGrn field value if set, zero value otherwise.
func (o *CustomerUnassignAgentRequest) GetAgentGrn() string {
	if o == nil || IsNil(o.AgentGrn) {
		var ret string
		return ret
	}
	return *o.AgentGrn
}

// GetAgentGrnOk returns a tuple with the AgentGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUnassignAgentRequest) GetAgentGrnOk() (*string, bool) {
	if o == nil || IsNil(o.AgentGrn) {
		return nil, false
	}
	return o.AgentGrn, true
}

// HasAgentGrn returns a boolean if a field has been set.
func (o *CustomerUnassignAgentRequest) HasAgentGrn() bool {
	if o != nil && !IsNil(o.AgentGrn) {
		return true
	}

	return false
}

// SetAgentGrn gets a reference to the given string and assigns it to the AgentGrn field.
func (o *CustomerUnassignAgentRequest) SetAgentGrn(v string) {
	o.AgentGrn = &v
}

// GetCustomerIds returns the CustomerIds field value if set, zero value otherwise.
func (o *CustomerUnassignAgentRequest) GetCustomerIds() []string {
	if o == nil || IsNil(o.CustomerIds) {
		var ret []string
		return ret
	}
	return o.CustomerIds
}

// GetCustomerIdsOk returns a tuple with the CustomerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUnassignAgentRequest) GetCustomerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerIds) {
		return nil, false
	}
	return o.CustomerIds, true
}

// HasCustomerIds returns a boolean if a field has been set.
func (o *CustomerUnassignAgentRequest) HasCustomerIds() bool {
	if o != nil && !IsNil(o.CustomerIds) {
		return true
	}

	return false
}

// SetCustomerIds gets a reference to the given []string and assigns it to the CustomerIds field.
func (o *CustomerUnassignAgentRequest) SetCustomerIds(v []string) {
	o.CustomerIds = v
}

func (o CustomerUnassignAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerUnassignAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.AgentGrn) {
		toSerialize["agentGrn"] = o.AgentGrn
	}
	if !IsNil(o.CustomerIds) {
		toSerialize["customerIds"] = o.CustomerIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerUnassignAgentRequest) UnmarshalJSON(data []byte) (err error) {
	varCustomerUnassignAgentRequest := _CustomerUnassignAgentRequest{}

	err = json.Unmarshal(data, &varCustomerUnassignAgentRequest)

	if err != nil {
		return err
	}

	*o = CustomerUnassignAgentRequest(varCustomerUnassignAgentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "agentGrn")
		delete(additionalProperties, "customerIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerUnassignAgentRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *CustomerUnassignAgentRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableCustomerUnassignAgentRequest struct {
	value *CustomerUnassignAgentRequest
	isSet bool
}

func (v NullableCustomerUnassignAgentRequest) Get() *CustomerUnassignAgentRequest {
	return v.value
}

func (v *NullableCustomerUnassignAgentRequest) Set(val *CustomerUnassignAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerUnassignAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerUnassignAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerUnassignAgentRequest(val *CustomerUnassignAgentRequest) *NullableCustomerUnassignAgentRequest {
	return &NullableCustomerUnassignAgentRequest{value: val, isSet: true}
}

func (v NullableCustomerUnassignAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerUnassignAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
