/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// checks if the CustomerBulkUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerBulkUpdateResponse{}

// CustomerBulkUpdateResponse struct for CustomerBulkUpdateResponse
type CustomerBulkUpdateResponse struct {
	CustomerIds []string `json:"customerIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerBulkUpdateResponse CustomerBulkUpdateResponse

// NewCustomerBulkUpdateResponse instantiates a new CustomerBulkUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerBulkUpdateResponse() *CustomerBulkUpdateResponse {
	this := CustomerBulkUpdateResponse{}
	return &this
}

// NewCustomerBulkUpdateResponseWithDefaults instantiates a new CustomerBulkUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerBulkUpdateResponseWithDefaults() *CustomerBulkUpdateResponse {
	this := CustomerBulkUpdateResponse{}
	return &this
}

// GetCustomerIds returns the CustomerIds field value if set, zero value otherwise.
func (o *CustomerBulkUpdateResponse) GetCustomerIds() []string {
	if o == nil || IsNil(o.CustomerIds) {
		var ret []string
		return ret
	}
	return o.CustomerIds
}

// GetCustomerIdsOk returns a tuple with the CustomerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerBulkUpdateResponse) GetCustomerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerIds) {
		return nil, false
	}
	return o.CustomerIds, true
}

// HasCustomerIds returns a boolean if a field has been set.
func (o *CustomerBulkUpdateResponse) HasCustomerIds() bool {
	if o != nil && !IsNil(o.CustomerIds) {
		return true
	}

	return false
}

// SetCustomerIds gets a reference to the given []string and assigns it to the CustomerIds field.
func (o *CustomerBulkUpdateResponse) SetCustomerIds(v []string) {
	o.CustomerIds = v
}

func (o CustomerBulkUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerBulkUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerIds) {
		toSerialize["customerIds"] = o.CustomerIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerBulkUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	varCustomerBulkUpdateResponse := _CustomerBulkUpdateResponse{}

	err = json.Unmarshal(data, &varCustomerBulkUpdateResponse)

	if err != nil {
		return err
	}

	*o = CustomerBulkUpdateResponse(varCustomerBulkUpdateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customerIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CustomerBulkUpdateResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *CustomerBulkUpdateResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableCustomerBulkUpdateResponse struct {
	value *CustomerBulkUpdateResponse
	isSet bool
}

func (v NullableCustomerBulkUpdateResponse) Get() *CustomerBulkUpdateResponse {
	return v.value
}

func (v *NullableCustomerBulkUpdateResponse) Set(val *CustomerBulkUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerBulkUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerBulkUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerBulkUpdateResponse(val *CustomerBulkUpdateResponse) *NullableCustomerBulkUpdateResponse {
	return &NullableCustomerBulkUpdateResponse{value: val, isSet: true}
}

func (v NullableCustomerBulkUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerBulkUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


