/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CustomerFindSubscriberByIdRequest struct for CustomerFindSubscriberByIdRequest
type CustomerFindSubscriberByIdRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	SubscriberId *string `json:"subscriberId,omitempty"`
}

// NewCustomerFindSubscriberByIdRequest instantiates a new CustomerFindSubscriberByIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFindSubscriberByIdRequest() *CustomerFindSubscriberByIdRequest {
	this := CustomerFindSubscriberByIdRequest{}
	return &this
}

// NewCustomerFindSubscriberByIdRequestWithDefaults instantiates a new CustomerFindSubscriberByIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFindSubscriberByIdRequestWithDefaults() *CustomerFindSubscriberByIdRequest {
	this := CustomerFindSubscriberByIdRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerFindSubscriberByIdRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindSubscriberByIdRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerFindSubscriberByIdRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerFindSubscriberByIdRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSubscriberId returns the SubscriberId field value if set, zero value otherwise.
func (o *CustomerFindSubscriberByIdRequest) GetSubscriberId() string {
	if o == nil || isNil(o.SubscriberId) {
		var ret string
		return ret
	}
	return *o.SubscriberId
}

// GetSubscriberIdOk returns a tuple with the SubscriberId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindSubscriberByIdRequest) GetSubscriberIdOk() (*string, bool) {
	if o == nil || isNil(o.SubscriberId) {
    return nil, false
	}
	return o.SubscriberId, true
}

// HasSubscriberId returns a boolean if a field has been set.
func (o *CustomerFindSubscriberByIdRequest) HasSubscriberId() bool {
	if o != nil && !isNil(o.SubscriberId) {
		return true
	}

	return false
}

// SetSubscriberId gets a reference to the given string and assigns it to the SubscriberId field.
func (o *CustomerFindSubscriberByIdRequest) SetSubscriberId(v string) {
	o.SubscriberId = &v
}

func (o CustomerFindSubscriberByIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.SubscriberId) {
		toSerialize["subscriberId"] = o.SubscriberId
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerFindSubscriberByIdRequest struct {
	value *CustomerFindSubscriberByIdRequest
	isSet bool
}

func (v NullableCustomerFindSubscriberByIdRequest) Get() *CustomerFindSubscriberByIdRequest {
	return v.value
}

func (v *NullableCustomerFindSubscriberByIdRequest) Set(val *CustomerFindSubscriberByIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFindSubscriberByIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFindSubscriberByIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFindSubscriberByIdRequest(val *CustomerFindSubscriberByIdRequest) *NullableCustomerFindSubscriberByIdRequest {
	return &NullableCustomerFindSubscriberByIdRequest{value: val, isSet: true}
}

func (v NullableCustomerFindSubscriberByIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFindSubscriberByIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


