/*
customer/customer.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// CustomerFindManyResponse struct for CustomerFindManyResponse
type CustomerFindManyResponse struct {
	Customers []CustomerCustomerResponse `json:"customers,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewCustomerFindManyResponse instantiates a new CustomerFindManyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFindManyResponse() *CustomerFindManyResponse {
	this := CustomerFindManyResponse{}
	return &this
}

// NewCustomerFindManyResponseWithDefaults instantiates a new CustomerFindManyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFindManyResponseWithDefaults() *CustomerFindManyResponse {
	this := CustomerFindManyResponse{}
	return &this
}

// GetCustomers returns the Customers field value if set, zero value otherwise.
func (o *CustomerFindManyResponse) GetCustomers() []CustomerCustomerResponse {
	if o == nil || isNil(o.Customers) {
		var ret []CustomerCustomerResponse
		return ret
	}
	return o.Customers
}

// GetCustomersOk returns a tuple with the Customers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindManyResponse) GetCustomersOk() ([]CustomerCustomerResponse, bool) {
	if o == nil || isNil(o.Customers) {
    return nil, false
	}
	return o.Customers, true
}

// HasCustomers returns a boolean if a field has been set.
func (o *CustomerFindManyResponse) HasCustomers() bool {
	if o != nil && !isNil(o.Customers) {
		return true
	}

	return false
}

// SetCustomers gets a reference to the given []CustomerCustomerResponse and assigns it to the Customers field.
func (o *CustomerFindManyResponse) SetCustomers(v []CustomerCustomerResponse) {
	o.Customers = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *CustomerFindManyResponse) GetNextPageToken() string {
	if o == nil || isNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFindManyResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || isNil(o.NextPageToken) {
    return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *CustomerFindManyResponse) HasNextPageToken() bool {
	if o != nil && !isNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *CustomerFindManyResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o CustomerFindManyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Customers) {
		toSerialize["customers"] = o.Customers
	}
	if !isNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerFindManyResponse struct {
	value *CustomerFindManyResponse
	isSet bool
}

func (v NullableCustomerFindManyResponse) Get() *CustomerFindManyResponse {
	return v.value
}

func (v *NullableCustomerFindManyResponse) Set(val *CustomerFindManyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFindManyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFindManyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFindManyResponse(val *CustomerFindManyResponse) *NullableCustomerFindManyResponse {
	return &NullableCustomerFindManyResponse{value: val, isSet: true}
}

func (v NullableCustomerFindManyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFindManyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


