/*
CDP Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer

import (
	"encoding/json"
)

// CustomerGetGroupByIdRequest struct for CustomerGetGroupByIdRequest
type CustomerGetGroupByIdRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	GroupId *string `json:"groupId,omitempty"`
}

// NewCustomerGetGroupByIdRequest instantiates a new CustomerGetGroupByIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerGetGroupByIdRequest() *CustomerGetGroupByIdRequest {
	this := CustomerGetGroupByIdRequest{}
	return &this
}

// NewCustomerGetGroupByIdRequestWithDefaults instantiates a new CustomerGetGroupByIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerGetGroupByIdRequestWithDefaults() *CustomerGetGroupByIdRequest {
	this := CustomerGetGroupByIdRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CustomerGetGroupByIdRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerGetGroupByIdRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CustomerGetGroupByIdRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CustomerGetGroupByIdRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *CustomerGetGroupByIdRequest) GetGroupId() string {
	if o == nil || isNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerGetGroupByIdRequest) GetGroupIdOk() (*string, bool) {
	if o == nil || isNil(o.GroupId) {
    return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *CustomerGetGroupByIdRequest) HasGroupId() bool {
	if o != nil && !isNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *CustomerGetGroupByIdRequest) SetGroupId(v string) {
	o.GroupId = &v
}

func (o CustomerGetGroupByIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerGetGroupByIdRequest struct {
	value *CustomerGetGroupByIdRequest
	isSet bool
}

func (v NullableCustomerGetGroupByIdRequest) Get() *CustomerGetGroupByIdRequest {
	return v.value
}

func (v *NullableCustomerGetGroupByIdRequest) Set(val *CustomerGetGroupByIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerGetGroupByIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerGetGroupByIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerGetGroupByIdRequest(val *CustomerGetGroupByIdRequest) *NullableCustomerGetGroupByIdRequest {
	return &NullableCustomerGetGroupByIdRequest{value: val, isSet: true}
}

func (v NullableCustomerGetGroupByIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerGetGroupByIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


